### ISSUE TITLE
Training Stops after first Epoch

### ISSUE THREAD

**Issue by maaft** [fangchangma/sparse-to-dense.pytorch#3]
Hi,
i am trying to train the model with
`python3 main.py -a resnet50 -d deconv3 -m rgbd -s 100`
on the nyudepthv2 dataset.

Here is the output of the program right after the first epoch is finished:
```

Train Epoch: 0 [5920/5948]      t_Data=0.004(0.004) t_GPU=0.093(0.093) RMSE=0.41(0.54) MAE=0.27(0.38) Delta1=0.888(0.762) REL=234.655(1369143557398969.500) Lg10=0.052(nan) 
=> output: results/NYUDataset.modality=rgbd.nsample=100.arch=resnet50.decoder=deconv3.criterion=l1.lr=0.01.bs=8
Train Epoch: 0 [5930/5948]      t_Data=0.004(0.004) t_GPU=0.093(0.093) RMSE=0.33(0.54) MAE=0.24(0.38) Delta1=0.941(0.762) REL=0.351(1366834725411658.500) Lg10=0.046(nan) 
=> output: results/NYUDataset.modality=rgbd.nsample=100.arch=resnet50.decoder=deconv3.criterion=l1.lr=0.01.bs=8
Train Epoch: 0 [5940/5948]      t_Data=0.004(0.004) t_GPU=0.091(0.093) RMSE=0.29(0.54) MAE=0.18(0.38) Delta1=0.965(0.763) REL=0.074(1366117206601379.500) Lg10=0.030(nan) 

Traceback (most recent call last):
  File "main.py", line 355, in <module>
    main()
  File "main.py", line 195, in main
    result, img_merge = validate(val_loader, model, epoch)
  File "main.py", line 299, in validate
    img_merge = utils.merge_into_row(input, target, depth_pred)
  File "/upb/departments/pc2/scratch/maaft/sparse-to-dense/utils.py", line 15, in merge_into_row
    img_merge = np.hstack([rgb, depth, pred])
  File "/root/anaconda3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 288, in hstack
    return _nx.concatenate(arrs, 1)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
GPU is a GTX1080ti.

Any idea what to do?

Best regards,
maaft

**Comment by fangchangma** [comment]
Thanks for reporting the issue. It was a bug in image saving when input modality is not rgb. The bug has been fixed.
